Algoritmo "Consumo"
// 
//  
// Descrição   : Calcula o Consumo médio de Combustível
// Autor(a)    : Kelvin Coelho Loiola
// Data atual  : 13/01/2022
Var
   distancia : inteiro
   combustivelGasto : real


Inicio
      escreva("Distancia percorrida: ")
      leia(distancia)
      
      escreva("Combistível gasto: ")
      leia(combustivelGasto)
      
      escreval("Consumo Médio = ", (distancia / combustivelGasto):1:3)

Fimalgoritmo