Algoritmo "Tabuada"
// Descrição   : Solicita ao usuário a entrada de um numero inteiro e
//               exibe a tabuada deste número.
// Autor(a)    : Kelvin Coelho Loiola
// Data atual  : 14/01/2022
Var
   i, n : inteiro
Inicio
      escreva("Deseja a tabuada para qual valor? ")
      leia(n)
      
      para i de 1 ate 10 faca
           escreval(n, " x ", i, " = ", n * i)
      fimpara

Fimalgoritmo